FROM python:3.8

RUN pip install --upgrade pip

WORKDIR /mkdocs

RUN --mount=target=/build/requirements.txt,source=requirements.txt \
    pip install -r /build/requirements.txt

ENTRYPOINT ["mkdocs"]
